version: 1.0.0-{build}
branches:
  only:
  - main
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
- ps: .\build\build.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_TAG_NAME
#before_test:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: '.\artifacts\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: ZXzm7TLt+2cLcS3yZ1pQ9KYg5zdRAA3vHCQEuuj8eDfsSNS1B78BvPBZahwEZEKj
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
      appveyor_repo_tag: true       # deploy on tag push only
